package com.example.demo.entity;
// Generated 2018-4-22 16:49:31 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FSkuclass generated by hbm2java
 */
@Entity
@Table(name = "f_skuclass", catalog = "gabdp")
public class FSkuclass implements java.io.Serializable {

	private String id;
	private String name;
	private String contentName;
	private String eshopId;
	private String roleName;
	private String tagLevel1Name;
	private String tagLevel1Id;
	private String tagLevel2Name;
	private String tagLevel2Id;
	private String tagLevel3Name;
	private String tagLevel3Id;
	private String tagLevel4Name;
	private String tagLevel4Id;

	public FSkuclass() {
	}


	public FSkuclass(String id, String name, String contentName, String eshopId, String roleName, String tagLevel1Name, String tagLevel1Id, String tagLevel2Name, String tagLevel2Id, String tagLevel3Name, String tagLevel3Id, String tagLevel4Name, String tagLevel4Id) {
       this.id = id;
       this.name = name;
       this.contentName = contentName;
       this.eshopId = eshopId;
       this.roleName = roleName;
       this.tagLevel1Name = tagLevel1Name;
       this.tagLevel1Id = tagLevel1Id;
       this.tagLevel2Name = tagLevel2Name;
       this.tagLevel2Id = tagLevel2Id;
       this.tagLevel3Name = tagLevel3Name;
       this.tagLevel3Id = tagLevel3Id;
       this.tagLevel4Name = tagLevel4Name;
       this.tagLevel4Id = tagLevel4Id;
    }

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name="?name")
    public String getName() {
        return this.name;
    }

	public void setName(String name) {
        this.name = name;
    }

	@Column(name = "content_name")
	public String getContentName() {
		return this.contentName;
	}

	public void setContentName(String contentName) {
		this.contentName = contentName;
	}

	@Column(name = "eshop_id")
	public String getEshopId() {
		return this.eshopId;
	}

	public void setEshopId(String eshopId) {
		this.eshopId = eshopId;
	}

	@Column(name = "role_name")
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "tag_level1_name")
	public String getTagLevel1Name() {
		return this.tagLevel1Name;
	}

	public void setTagLevel1Name(String tagLevel1Name) {
		this.tagLevel1Name = tagLevel1Name;
	}

	@Column(name = "tag_level1_id")
	public String getTagLevel1Id() {
		return this.tagLevel1Id;
	}

	public void setTagLevel1Id(String tagLevel1Id) {
		this.tagLevel1Id = tagLevel1Id;
	}

	@Column(name = "tag_level2_name")
	public String getTagLevel2Name() {
		return this.tagLevel2Name;
	}

	public void setTagLevel2Name(String tagLevel2Name) {
		this.tagLevel2Name = tagLevel2Name;
	}

	@Column(name = "tag_level2_id")
	public String getTagLevel2Id() {
		return this.tagLevel2Id;
	}

	public void setTagLevel2Id(String tagLevel2Id) {
		this.tagLevel2Id = tagLevel2Id;
	}

	@Column(name = "tag_level3_name")
	public String getTagLevel3Name() {
		return this.tagLevel3Name;
	}

	public void setTagLevel3Name(String tagLevel3Name) {
		this.tagLevel3Name = tagLevel3Name;
	}

	@Column(name = "tag_level3_id")
	public String getTagLevel3Id() {
		return this.tagLevel3Id;
	}

	public void setTagLevel3Id(String tagLevel3Id) {
		this.tagLevel3Id = tagLevel3Id;
	}

	@Column(name = "tag_level4_name")
	public String getTagLevel4Name() {
		return this.tagLevel4Name;
	}

	public void setTagLevel4Name(String tagLevel4Name) {
		this.tagLevel4Name = tagLevel4Name;
	}

	@Column(name = "tag_level4_id")
	public String getTagLevel4Id() {
		return this.tagLevel4Id;
	}

	public void setTagLevel4Id(String tagLevel4Id) {
		this.tagLevel4Id = tagLevel4Id;
	}

}
