package com.example.demo.entity;
// Generated 2018-4-22 18:03:03 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MRelateSalesItemArea generated by hbm2java
 */
@Entity
@Table(name = "m_relate_sales_item_area", catalog = "gabdp")
public class MRelateSalesItemArea implements java.io.Serializable {

	private Long id;
	private String storeId;
	private String storeName;
	private String provinceCode;
	private String adCode;
	private String itemId;
	private String mykey;
	private Date date;

	public MRelateSalesItemArea() {
	}

	public MRelateSalesItemArea(String storeName, String mykey, Date date) {
		this.storeName = storeName;
		this.mykey = mykey;
		this.date = date;
	}

	public MRelateSalesItemArea(String storeId, String storeName, String provinceCode, String adCode, String itemId,
			String mykey, Date date) {
		this.storeId = storeId;
		this.storeName = storeName;
		this.provinceCode = provinceCode;
		this.adCode = adCode;
		this.itemId = itemId;
		this.mykey = mykey;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "store_id", length = 32)
	public String getStoreId() {
		return this.storeId;
	}

	public void setStoreId(String storeId) {
		this.storeId = storeId;
	}

	@Column(name = "store_name", nullable = false, length = 20)
	public String getStoreName() {
		return this.storeName;
	}

	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}

	@Column(name = "province_code", length = 20)
	public String getProvinceCode() {
		return this.provinceCode;
	}

	public void setProvinceCode(String provinceCode) {
		this.provinceCode = provinceCode;
	}

	@Column(name = "ad_code", length = 20)
	public String getAdCode() {
		return this.adCode;
	}

	public void setAdCode(String adCode) {
		this.adCode = adCode;
	}

	@Column(name = "item_id")
	public String getItemId() {
		return this.itemId;
	}

	public void setItemId(String itemId) {
		this.itemId = itemId;
	}

	@Column(name = "mykey", nullable = false)
	public String getMykey() {
		return this.mykey;
	}

	public void setMykey(String mykey) {
		this.mykey = mykey;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
