package com.example.demo.entity;
// Generated 2018-4-22 17:41:59 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TCtsType generated by hbm2java
 */
@Entity
@Table(name = "t_cts_type", catalog = "gabdp")
public class TCtsType implements java.io.Serializable {

	private Long id;
	private String type;
	private String code;
	private long parentId;
	private String parentCode;
	private String name;
	private String desc;
	private String demo;
	private Boolean status;

	public TCtsType() {
	}

	public TCtsType(String type, long parentId, String name) {
		this.type = type;
		this.parentId = parentId;
		this.name = name;
	}

	public TCtsType(String type, String code, long parentId, String parentCode, String name, String desc, String demo,
			Boolean status) {
		this.type = type;
		this.code = code;
		this.parentId = parentId;
		this.parentCode = parentCode;
		this.name = name;
		this.desc = desc;
		this.demo = demo;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "type", nullable = false, length = 16)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "code", length = 20)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "parent_id", nullable = false)
	public long getParentId() {
		return this.parentId;
	}

	public void setParentId(long parentId) {
		this.parentId = parentId;
	}

	@Column(name = "parent_code", length = 20)
	public String getParentCode() {
		return this.parentCode;
	}

	public void setParentCode(String parentCode) {
		this.parentCode = parentCode;
	}

	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "desc", length = 50)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@Column(name = "demo", length = 50)
	public String getDemo() {
		return this.demo;
	}

	public void setDemo(String demo) {
		this.demo = demo;
	}

	@Column(name = "status")
	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

}
